Traceback (most recent call last):
  File "/home/pi/pypgm/all_only_one_charging.py", line 285, in <module>
    discharging(baterry, pinrelebat, pinrelebat2, minvbat)
  File "/home/pi/pypgm/all_only_one_charging.py", line 204, in discharging
    read_ina()
  File "/home/pi/pypgm/all_only_one_charging.py", line 64, in read_ina
    vin = float("{:.2f}".format(ina3221.bus_voltage(1)))
  File "/home/pi/.local/lib/python3.9/site-packages/barbudor_ina3221/lite.py", line 230, in bus_voltage
    value = self._to_signed(self.read(_REG_BUS_VOLTAGE_CH[channel])) / 8
  File "/home/pi/.local/lib/python3.9/site-packages/barbudor_ina3221/lite.py", line 178, in read
    i2c.write_then_readinto(buf, buf, out_end=1, in_start=1)
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_bus_device/i2c_device.py", line 141, in write_then_readinto
    self.i2c.writeto_then_readfrom(
  File "/home/pi/.local/lib/python3.9/site-packages/busio.py", line 192, in writeto_then_readfrom
    return self._i2c.writeto_then_readfrom(
  File "/home/pi/.local/lib/python3.9/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 90, in writeto_then_readfrom
    readin = self._i2c_bus.read_i2c_block_data(
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_PureIO/smbus.py", line 275, in read_i2c_block_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
OSError: [Errno 121] Remote I/O error
